services:
  - type: web
    name: star-health-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: star-health-db
          property: connectionString
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RECEIVER_EMAIL
        sync: false

databases:
  - name: star-health-db
    plan: free
